fixed uri verification function

diff --git a/bin/konaste b/bin/konaste
--- a/bin/konaste
+++ b/bin/konaste
@@ -182,39 +182,44 @@ parse_flags() {
 ####################################################################################################
 
 function verify_uri() {
-	[[ -z "$launchURI" || -z "$toPlay" ]] && return 127
+	[[ -z "${launchUri}" || -z "$toPlay" ]] && return 127
 
-	if [[ "$launchURI" =~ ^bm2dxinf:// || "$launchURI" =~ ^konaste.*:// ]]; then
+	if [[ "${launchUri}" =~ ^bm2dxinf:// || "${launchUri}" =~ ^konaste.*:// ]]; then
 		if [[ "$toPlay" == 'iidx' ]]; then
-			if [[ "$launchURI" == konaste.*://* ]]; then
-				error "${GAME_TITLE} cannot be started with a ${launchURI%://*}:// URI"
+			if [[ "${launchUri}" == konaste.*://* ]]; then
+				log error "$(get_title) cannot be started with a ${launchUri%://*}:// URI"
 				return 1
 			fi
 
 			# Work our way up
-			uriContent="${launchURI##*://}"
+			uriContent="${launchUri##*://}"
 			if [[ "$uriContent" =~ login\?tk= ]]; then
 				uriContent="${uriContent##*login\?tk=}"
 				uriToken="${uriContent%\&*}"
 				#uriMode=$(tr -dc '[:alpha:]' <<< "${uriContent##*\&}")
 
 				if [[ "${#uriToken}" -ne 64 ]]; then
-					error "Token length is not equal to 64"
+					log error "Token length is not equal to 64"
 					return 2
+				fi
+
+				if [[ $(grep -E '[^0-9a-f]' <<< "$uriToken") ]]; then
+					log error "Invalid URI for $(get_title) provided"
+					return 3
 				fi
 
 				uriMode=$(grep -Eo '&.*$' <<< "$uriContent" | tr -dc '[:alpha:]')
 				if [[ -z "$uriMode" ]]; then
 					# If you don't include the thing at the end, beatmania IIDX INFINITAS will
 					# always assume it is being launched in release mode (rel).
-					warning "No mode specified! Assuming release mode..."
-					launchURI+='&rel='
+					log warning "No mode specified! Assuming release mode..."
+					launchUri+='&rel='
 
 					unset uriMode uriContent uriToken
 					return 0
 				else
 					if [[ "$uriMode" != 'rel' && "$uriMode" != 'trial' ]]; then
-						error "Unrecognized mode for ${GAME_TITLE} specified: $uriMode" >&2
+						log error "Unrecognized mode for $(get_title) specified: $uriMode" >&2
 						return 4
 					else
 						unset uriMode uriContent uriToken
@@ -223,20 +228,20 @@ function verify_uri() {
 				fi
 			fi
 
-			echo "Malformed URI for ${GAME_TITLE} provided" >&2
+			echo "Malformed URI for $(get_title) provided" >&2
 			return 1
 		else
-			if [[ "$launchURI" == bm2dxinf://* ]]; then
-				error "${GAME_TITLE} cannot be started with a ${launchURI%://*}:// URI"
+			if [[ "$launchUri" == bm2dxinf://* ]]; then
+				log error "$(get_title) cannot be started with a ${launchUri%://*}:// URI"
 				return 1
 			fi
-			uriId=$(cut -d'.' -f2 2>/dev/null <<< "${launchURI%://*}")
+			uriId=$(cut -d'.' -f2 2>/dev/null <<< "${launchUri%://*}")
 			if [[ "$uriId" != $(cut -d'.' -f2 2>/dev/null <<< "$URI") ]]; then
-				error "Invalid Konaste URI: konaste.${uriId}"
+				log error "Invalid Konaste URI: konaste.${uriId}"
 				return 2
 			fi
 
-			uriToken=( $(sed -e 's:\-:\ :g' 2>/dev/null <<< "${launchURI##*://}") )
+			uriToken=( $(sed -e 's:\-:\ :g' 2>/dev/null <<< "${launchUri##*://}") )
 			# Now go through all the entries
 			for (( i=0; i<5; i++ )); do
 				case $i in
@@ -246,7 +251,7 @@ function verify_uri() {
 				esac
 
 				if [[ $? -ne 0 ]]; then
-					error "Malformed URI for ${GAME_TITLE} provided"
+					log error "Malformed URI for $(get_title) provided"
 					return 3
 				fi
 			done
@@ -255,7 +260,7 @@ function verify_uri() {
 			return 0
 		fi
 	else
-		error "Invalid URI specified: $launchURI"
+		log error "Invalid URI specified: $launchUri"
 		return 1
 	fi
 }
@@ -284,7 +289,6 @@ function get_registry_key() {
 }
 
 function get_launcher_for_game() {
-
 	# I think just trying to look for the launcher within the filesystem would've
 	# been quicker, but I REALLY want this to see if the file exists.
 	[[ -z "$toPlay" ]] && return 1
@@ -559,6 +563,9 @@ launch_game() {
 	log info "Launching $(get_title)..."
 
 	verify_uri # verifies the URI
+	if [[ $? -ne 0 ]]; then
+		exit 1
+	fi
 
 	declare -a launchParams=( )
 
