update

diff --git a/bin/konaste b/bin/konaste
--- a/bin/konaste
+++ b/bin/konaste
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-VERSION='0.2.1'
+VERSION='0.2.2'
 #
 # Konaste Linux: A Bash script for installing and playing KONAMI Amusement Game
 # Station (Konaste) games on Linux-based operating systems, using Wine.
@@ -17,16 +17,6 @@ VERSION='0.2.1'
 # Konaste titles have been tested, and may exhibit some undocumented bugs.
 #
 
-#
-# HOW IT WORKS:
-# 1. User selects game launcher from DE/WM
-# 2. Konaste Linux initializes a Wineprefix, if necessary
-# 3. Search the prefix's registry for the game's InstallDir key
-# 4. Download and run the game installer, if not installed
-# 5. Open the game's launch page in a browser, if no URI is provided
-# 6. Start the game's launcher, with the URI as an argument
-# 7. GO BONGA~!
-#
 
 WINE="$(command -v wine)"
 WINEBOOT="$(command -v wineboot)"
@@ -36,11 +26,6 @@ MSIEXTRACT="$(command -v msiextract)"
 PW_LOOPBACK="$(command -v pw-loopback)"
 PACTL="$(command -v pactl)"
 WGET="$(command -v wget)"
-GAMEMODE="$(command -v gamemoderun)"
-GAMESCOPE="$(command -v gamescope)"
-_MANGOHUD="$(command -v mangohud)" # this would overwrite the default MANGOHUD env variable so the _ is necessary
-
-KDIALOG="$(command -v kdialog)"
 ZENITY="$(command -v zenity)"
 
 DEFAULT_PREFIX_LOCATION="$HOME/.local/share/konaste"
@@ -90,26 +75,7 @@ show_help() {
 		echo -e "  list  List installed games"
 		echo -e "  help  Show this message"
 		echo -e "\n\033[1mFlags: \033[0m"
-		echo -en "  --silent            Skip the game installer and use defaults "
-		[[ ! -x "${MSIEXTRACT}" ]] && echo -en '\033[38;5;1m(unavailable)\033[0m'
-		echo -en "\n  --gamescope         Run through a microcompositor to work around some display quirks "
-		if [[ ! -x "${GAMESCOPE}" ]]; then
-			echo -e '\033[38;5;1m(not installed)\033[0m'
-		else
-			echo -e '\033[38;5;2m(installed)\033[0m'
-		fi
-		echo -en "  --gamemode          Apply temporary OS-level tweaks to improve performance "
-		if [[ ! -x "${GAMEMODE}" ]]; then
-			echo -e '\033[38;5;1m(not installed)\033[0m'
-		else
-			echo -e '\033[38;5;2m(installed)\033[0m'
-		fi
-		echo -en "  --mangohud          Show stats related to FPS and hardware utilization while playing "
-		if [[ ! -x "${_MANGOHUD}" ]]; then
-			echo -e '\033[38;5;1m(not installed)\033[0m'
-		else
-			echo -e '\033[38;5;2m(installed)\033[0m'
-		fi
+		echo -e "  --silent            Skip the game installer and use defaults (requires msitools)"
 		echo -e "  --wine-vd           Run through Wine's virtual desktop"
 		echo -e "\n\033[1mThe following flags are experimental and can break things:\033[0m"
 		echo -e "  --disable-dxvk      Use Wine's built-in DirectX libraries instead of DXVK"
@@ -179,9 +145,6 @@ parse_flags() {
 			# Install Flags
 			--silent) silentInstall=1 ;;
 			# Gameplay flags
-			--gamemode) useGamemode=1 ;;
-			--gamescope) useGamescope=1 ;;
-			--mangohud) useMangohud=1 ;;
 			--wine-vd) useWineVD=1 ;;
 			# DANGER flags:
 			--disable-dxvk) noDXVK=1 ;;
@@ -194,47 +157,6 @@ parse_flags() {
 
 		shift
 	done
-
-	# Set defaults if not defined
-
-	if [[ $useGamemode -eq 1 ]]; then
-		if [[ ! -x "${GAMEMODE}" ]]; then
-			log warning "--gamemode flag specified, but gamemoderun was not found on your system"
-			declare -gr useGamemode=0
-		fi
-	fi
-
-	# Enable Gamescope and set flags
-	if [[ $useGamescope -eq 1 ]]; then
-		if [[ ! -x "${GAMESCOPE}" ]]; then
-			log warning "--gamescope flag specified, but gamescope was not found on your system"
-			declare -gr useGamescope=0 # disable this and set it to read only
-		else
-			declare -ag GAMESCOPE_PARAMS=( "${GAMESCOPE}" -w 1920 -h 1080 )
-			if [[ $useMangohud -eq 1 ]]; then
-				if [[ -x "${_MANGOHUD}" ]]; then
-					# gamescope devs want you to use this.
-					GAMESCOPE_PARAMS+=( --mangoapp )
-				else
-					log warning "--mangohud flag specified, but mangohud was not found on your system"
-					declare -gr useMangohud=0
-				fi
-			fi
-			case "$toPlay" in
-				iidx|sdvx|ddr) GAMESCOPE_PARAMS+=( -r 120 --framerate-limit 120 ) ;; # these games support 120fps
-				bombergirl)    GAMESCOPE_PARAMS+=( -r 60 --adaptive-sync ) ;; # since bonga is a unity game
-				*)             GAMESCOPE_PARAMS+=( -r 60 --framerate-limit 60 ) ;;
-			esac
-			GAMESCOPE_PARAMS+=( -f -- )
-		fi
-	fi
-
-	if [[ $useMangohud -eq 1 ]]; then
-		if [[ ! -x "${_MANGOHUD}" ]]; then
-			log warning "--mangohud flag specified, but mangohud was not found on your system"
-			declare -gr useMangohud=0
-		fi
-	fi
 
 	if [[ $useWayland -eq 1 ]]; then
 		if [[ $XDG_SESSION_TYPE	!= 'wayland' ]]; then
@@ -250,19 +172,44 @@ parse_flags() {
 ####################################################################################################
 ####################################################################################################
 
+function get_registry_key() {
+	[[ -z "$1" ]] && return 126
+
+	if [[ -z "$2" ]]; then
+		k="$(WINEDEBUG='-all' "${WINE}" reg query "${1}" '/ve' '/reg:64')"
+	else
+		k="$(WINEDEBUG='-all' "${WINE}" reg query "${1}" '/v' "${2}" '/reg:64')"
+	fi
+
+	if [[ $? -ne 0 ]]; then
+		return 1
+	fi
+
+	k="$(echo "${k}" | tr -dc '[:print:]' | sed 's:\ \ \ \ :\n:g' | tail -n+4)"
+	if [[ "$k" == '(value not set)' ]]; then
+		echo ""
+	else
+		echo "${k}"
+	fi
+
+	return 0
+}
+
 function get_launcher_for_game() {
+	# I think just trying to look for the launcher within the filesystem would've
+	# been quicker, but I REALLY want this to see if the file exists.
 	[[ -z "$toPlay" ]] && return 1
-	# FIXME: Find a better way to get values from the Windows registry
-	# Even though this does "work", it's by no means perfect, and I've already fried my ADHD brain
-	# trying to learn how regular expressions work.
-	local k="$(WINEDEBUG='-all' "${WINE}" reg query "HKLM\\SOFTWARE\\KONAMI\\$(get_game_information dirtitle)" /v 'InstallDir' '/reg:64' | awk '/REG_/ {print substr($0, index($0,$3))}')"
-	if [[ -n "$k" ]]; then
+
+	k="$(get_registry_key "HKLM\\SOFTWARE\\KONAMI\\$(get_game_information dirtitle)" 'InstallDir')"
+	if [[ -n "${k}" ]]; then
 		path="$("${WINEPATH}" -u "${k}")"
-		cd "${path:0:-1}" 2>/dev/null
-		[[ -f launcher/modules/"$(get_game_information launcher)".exe ]] && {
-			echo "$(${WINEPATH} -w launcher/modules/$(get_game_information launcher).exe)"
-			return 0
-		}
+		if [[ -d "${path}" ]]; then
+			cd "${path}"
+			if [[ -f launcher/modules/"$(get_game_information launcher)".exe ]]; then
+				echo "$("${WINEPATH}" -w launcher/modules/"$(get_game_information launcher)".exe)"
+				return 0
+			fi
+		fi
 	fi
 
 	return 1
@@ -316,7 +263,7 @@ function get_game_information() {
 		ddr)
 			GAME_TITLE='DanceDanceRevolution GRAND PRIX'
 			DIR_TITLE='DanceDanceRevolution'
-			SIMPLE_NAME="ddr-gp"
+			SIMPLE_NAME="ddr-grandprix"
 			INSTALLER_LINK="https://d2el0dli9l0x2p.cloudfront.net/installer/ddr_installer_2022012601.msi"
 			LAUNCH_PAGE="http://p.eagate.573.jp/game/konasteapp/API/login/login.html?game_id=ddr"
 			LAUNCHER_NAME='launcher'
@@ -388,22 +335,6 @@ function get_game_information() {
 ####################################################################################################
 ####################################################################################################
 
-list_games() {
-	get() {
-		toPlay="$1"
-		[[ -n "$(get_launcher_for_game)" ]] && echo "$toPlay"
-	}
-
-	get 'iidx'
-	get 'sdvx'
-	get 'ddr'
-	get 'gitadora'
-	get 'popn'
-	get 'nostalgia'
-	get 'bombergirl'
-	exit 0
-}
-
 prepare_wineprefix() {
 	# Create the Wineprefix if it does not exist
 	if [[ ! -e "${WINEPREFIX}" && ! -f "${WINEPREFIX}/system.reg" ]]; then
@@ -415,7 +346,7 @@ prepare_wineprefix() {
 		"${WINEBOOT}" -u 2>/dev/null
 	fi
 
-	DXVK_LINK="https://github.com/doitsujin/dxvk/releases/download/v2.5.3/dxvk-2.5.3.tar.gz"
+	DXVK_LINK="https://github.com/doitsujin/dxvk/releases/download/v2.6.2/dxvk-2.6.2.tar.gz"
 	VCR2010_LINK="https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x64.exe"
 
 	# Add the fonts so Japanese/Chinese characters render properly
@@ -518,14 +449,6 @@ prepare_wineprefix() {
 	log ok "${PREFIX_INIT}" >&2
 }
 
-
-
-
-
-
-
-
-
 launch_game() {
 	[[ -z "$toPlay" ]] && exit 1
 	log info "Launching $(get_title)..."
@@ -536,69 +459,77 @@ launch_game() {
 		# Use Wine's built-in DirectX libraries instead of the ones from DXVK
 		log warning "DXVK has been disabled. You may encounter glitched/missing graphics while playing $(get_title)!"
 		export WINEDLLOVERRIDES="${WINEDLLOVERRIDES};d3d9=b;d3d11=b;dxgi=b"
-	else
-		export DXVK_LOG_LEVEL='error' # Cut down on DXVK messages in your terminal
 	fi
+
+	# Warn the user if playing an untested game
+	case "$toPlay" in
+		iidx|sdvx|bombergirl) ;;
+		*)
+			log warning "$(get_title) has not been fully tested. Expect issues"
+			UNTESTED_WARNING="$(get_title) has not been tested by the developer. Any issues within this game should be reported on the Konaste Linux GitHub page, which can be found at:\n\nhttps://github.com/mizztgc/konaste-linux"
+
+			[[ -x "${ZENITY}" ]] && "${ZENITY}" --warning \
+				--title "Untested Game Warning" \
+				--width 400 \
+				--text "${UNTESTED_WARNING}" 2>/dev/null
+
+			unset UNTESTED_WARNING
+			;;
+	esac
 
 	# Due to how Wayland is coded, it causes IIDX INFINITAS to fail to find a suitable display mode if your refresh rate
 	# is set to anything other than 60 or 120Hz, so this warning is absolutely necessary.
 	if [[ "$toPlay" == 'iidx' && "$XDG_SESSION_TYPE" == 'wayland' && $useGamescope -ne 1 ]]; then
-		IIDX_WAYLAND_WARNING="You appear to be on a Wayland session provided by ${XDG_CURRENT_DESKTOP}. Due to how Wayland is coded, it only exposes your currently set refresh rate to applications, and because beatmania IIDX INFINITAS cannot automatically find a suitable mode, it will throw a display initialization error on startup. Before clicking 'OK', ensure that your refresh rate is set to 60Hz (or 120Hz if supported by your display)."
+		log warning "Wayland detected; expect issues"
+		IIDX_WAYLAND_WARNING="You appear to be on a Wayland session provided by ${XDG_CURRENT_DESKTOP}. Due to how Wayland is coded, it only exposes your currently set refresh rate to applications, and because beatmania IIDX INFINITAS cannot automatically find a suitable mode, it will throw a display initialization error on startup.\n\nBefore clicking 'OK', ensure that your refresh rate is set to 60Hz (or 120Hz if supported by your display)."
 
-		case "$dialog" in
-			kdialog) "${KDIALOG}" --title "Wayland Warning" --sorry "${IIDX_WAYLAND_WARNING}" 2>/dev/null ;;
-			zenity) "${ZENITY}" --warning --title "Wayland Warning" --text "${IIDX_WAYLAND_WARNING}" 2>/dev/null ;;
-			*) ;;
-		esac
-
+		[[ -x "${ZENITY}" ]] && "${ZENITY}" --warning --title "Wayland Warning" --text "${IIDX_WAYLAND_WARNING}" 2>/dev/null
 		unset IIDX_WAYLAND_WARNING
 	fi
 
+	# If the user has specified the --disable-loopback flag, do not enable the loopback device.
+	# But then again, bombergirl uses Unity, so it's (probably) using DirectSound or whatever
+	# that engine uses by default.
 	if [[ $noLoopback -ne 1 ]]; then
-		# The BEMANI games require a loopback device for audio to work.
-		# Bomber Girl uses a proper game engine (Unity) and doesn't need such workarounds.
-		# Thanks for making things difficult, konmai!
 		if [[ "$toPlay" != 'bombergirl' ]]; then
 			[[ -z "${PW_LOOPBACK}" ]] && log error "Missing PipeWire executable: pw-loopback" && exit 1
 			[[ -z "${PACTL}" ]] && log error "Missing dependency: libpulse" && exit 1
 
-			# I may have had help from ChatGPT for this part (damn regular expressions...)
-			current_samplerate=$($PACTL info | grep -w 'Default Sample Specification:' | sed 's/.* \([0-9]*\)Hz/\1/')
+			# Regular expressions annoy me...
+			current_samplerate=$("${PACTL}" info | grep -Eo '[0-9]{5,6}Hz' | tr -dc '[:digit:]')
 			if [[ "$current_samplerate" -ne 44100 ]]; then
-				log warning "Audio sample rate detected at ${current_samplerate}Hz. Enabling loopback device..."
+				#log warning "Audio sample rate detected at ${current_samplerate}Hz. Enabling loopback device..."
 				"${PW_LOOPBACK}" -m '[ FL FR ]' --capture-props='media.class=Audio/Sink node.name=konaste node.description=Konaste audio.rate=44100' &
-				[[ $? -eq 0 ]] && log info "Successfully enabled PipeWire loopback device" >&2 && export PULSE_SINK=konaste
+				PW_LOOPBACK_PID=$!
+
+				export PULSE_SINK=konaste
 			else
 				log info "Audio sample rate detected at 44100Hz. Not creating loopback device..." >&2
 			fi
 			unset current_samplerate
 		fi
 	else
-		[[ "$toPlay" != 'bombergirl' ]] && log warning "--disable-loopback flag specified! You may not have audio while playing $(get_title)!"
-	fi
-
-	# Add extra executables to launch parameters
-	[[ $useGamemode -eq 1 ]] && launchParams+=( "${GAMEMODE}" )
-	if [[ $useGamescope -eq 1 && $useMangohud -eq 1 ]]; then
-		# mangohud support is already in the gamescope params
-		launchParams+=( "${GAMESCOPE_PARAMS}" )
-	elif [[ $useMangohud -eq 1 ]]; then
-		# just throw in mangohud
-		launchParams+=( "${_MANGOHUD}" )
+		if [[ "$toPlay" != 'bombergirl' ]]; then
+			log warning "--disable-loopback flag specified! You may not have audio while playing $(get_title)!"
+		fi
 	fi
 
 	launchParams+=( "${WINE}" start '/high' '/wait' )
 	[[ $useWineVD -eq 1 ]] && launchParams+=( explorer '/desktop=Konaste,1920x1080' )
 
-	# The time has finally come.
+	# And we've finally made it to the part where we launch everything.
+	# LANG is set to Japanese so that text isn't garbled.
 	LANG='ja_JP.UTF-8' "${launchParams[@]}" "${launcher}" "${launchUri}"
-	"${WINESERVER}" -w
+	"${WINESERVER}" -w # This is to wait for all the processes launched by Wine to terminate
 
 	# Kill the loopback device if it's running
-	if [[ $(jobs | wc -l) -gt 0 ]]; then
-		kill -15 $(jobs -p)
+	if [[ ! -z $PW_LOOPBACK_PID ]]; then
+		log info "Terminating loopback device..."
+		kill $PW_LOOPBACK_PID
 		if [[ $? -eq 0 ]]; then
-			log info "Terminated PipeWire loopback device"
+			log ok "Terminated loopback device"
+		else
+			log error "Failed to terminate loopback device. Consider manually terminating the pw-loopback process."
 		fi
 	fi
 
@@ -606,16 +537,6 @@ launch_game() {
 	[[ "$toPlay" == 'iidx' ]] && echo -e "\n\033[1;95mThank you for playing...\033[0m\n"
 	exit 0 # exit with a code of 0 in case the above fails (this would return a non-zero value, indicating an "error")
 }
-
-
-
-
-
-
-
-
-
-
 
 install_game() {
 	[[ -z "${WGET}" ]] && error "Missing dependency: wget" && exit 1
@@ -704,51 +625,8 @@ install_game() {
 }
 
 main() {
-	# Warn if running as the root user.
-	[[ $EUID -eq 0 ]] && log warning "Avoid running this script as root/sudo."
-
-	block_gamescope() {
-		if [[ $GAMESCOPE_WAYLAND_DISPLAY || $XDG_CURRENT_DESKTOP == 'gamescope' ]]; then
-			# Add \n to improve visibility because gamescope likes to log a lot.
-			echo
-			log error "Do not run this script directly through a gamescope session. If you do intend on using gamescope, pass --gamescope as an argument.\n"
-			exit 127
-		fi
-	}
-
-	block_gamemode() {
-		if [[ $(env | grep -w 'libgamemodeauto.so.0') ]]; then
-			log error "Do not run this script directly through gamemoderun. If you do intend on using gamemoded, pass --gamemode as an argument."
-			exit 127
-		fi
-	}
-
-	block_mangohud() {
-		if [[ $MANGOHUD -eq 1 && $(env | grep -w mangohud) ]]; then
-			log error "Do not run this script directly through mangohud. If you do intend on using mangohud, pass --mangohud as an argument."
-			exit 127
-		fi
-	}
-
-	if [[ "$XDG_CURRENT_DESKTOP" == 'KDE' && -x "${KDIALOG}" ]]; then
-		dialog='kdialog'
-	elif [[ "$XDG_CURRENT_DESKTOP" == 'GNOME' && -x "${ZENITY}" ]]; then
-		dialog='zenity'
-	elif [[ -x "${ZENITY}" ]]; then
-		dialog='zenity'
-	elif [[ -x "${KDIALOG}" ]]; then
-		dialog='kdialog'
-	else
-		log warning "No dialog handler detected!"
-	fi
-
-
-
-	# Terminate if either one of these are running
-	block_gamescope
-	block_gamemode
-	block_mangohud
-
+	# Terminate if running as root
+	[[ $EUID -eq 0 ]] && log error "Do not run Konaste Linux as root/sudo." && exit 127
 	parse_flags "$@"
 
 	export WINEPREFIX="${DEFAULT_PREFIX_LOCATION}"
